// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://uldnqunqeibvocxsbkhb.supabase.co";
const SUPABASE_ANON_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVsZG5xdW5xZWlidm9jeHNia2hiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE5MDgxNjgsImV4cCI6MjA1NzQ4NDE2OH0.q4yP7fQWPRC2MEE3j5LTFfPCCeFFRridDnn_II6Us0I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Create a Supabase client for public operations
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY, {
  auth: {
    autoRefreshToken: true,
    persistSession: true,
    detectSessionInUrl: true,
    storageKey: 'uptowngym.auth.token' // Use our domain convention
  }
});

// Create a Supabase admin client for privileged operations (only used in secure contexts)
export const createAdminClient = (serviceRoleKey: string) => {
  return createClient<Database>(SUPABASE_URL, serviceRoleKey, {
    auth: {
      autoRefreshToken: false,
      persistSession: false,
      detectSessionInUrl: false
    }
  });
};